### ISSUE TITLE
"view on lichess" error

### ISSUE THREAD

**Issue by noamhacker** [jes/chess-steg#1]
The "view on lichess" button leads to an error page on lichess.org/import:
> Cross origin request forbidden

I believe it should redirect to lichess.org/paste instead

**Comment by jes** [comment]
FWIW, this works in Firefox.
I wonder if there's a way to try to do the form submission, and if the form submission gets blocked then explain to the user what they need to do?
Or alternatively is there a way for us to do the cross-origin request in Chrome without lichess cooperating? Or alternatively what would lichess need to do in order to allow cross-origin requests to /paste?
